### PR TITLE
Add possiblity to send commands via hassio_stdin service

### PR DESCRIPTION
**Pull request by grimpy**
Currently we implemented unlock which will unlock the door.

Other changes:
get rid of run.sh as we need the main process to read stdin directly

Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

### CODE REVIEW

**Comment by pergolafabio** [comment]
i had to encode it again, otherwise i got login failed

`user_id = HCNetSDK.NET_DVR_Login_V30(config["ip"].encode('utf-8'), 8000, config["username"].encode('utf-8'), config["password"].encode('utf-8'), device_info)`

also need to use 
`os.system("echo Hikvision SDK Add-on started! Listening for events...")  `

instead of prints, for some reason, i dont see that text in the addon log if i use print :-)

anway, tried to use this command below, but doesnt do anything, my guess its not reaching the addon

can i use another command to send to the container? maybe from the ssh container?

```
service: hassio.addon_stdin
data:
  addon: local_hikvision_sdk
  input: unlock
```

**Comment by pergolafabio** [comment]
also added to config.json => not sure if its needed :-)

**Comment by grimpy** [comment]
Can you try to add a newline in the input?

input: "unlock\n"


Since the code reads lines... It's possible aswell that you need to
encode the result or compare with b'unlock'



—

**Comment by pergolafabio** [comment]
hmm, doesnt change
is there no docker command for it? so i can try from the SSH addon first 

something like: 
docker exec addon_local_hikvision_sdk echo unlock

**Comment by grimpy** [comment]
I'm afraid that won't work.
Is there another way I can reach out to you on chat to make this a bit quicker?
I do believe it needs to be `"stdin": true` withouth the quotes around the true so it's a boolean not string.

Its strange os.system would be printed and print wouldn't both should be redirected to the same output

**Comment by pergolafabio** [comment]
discord? username : Fabio Pergola#9662

**Comment by pergolafabio** [comment]
updated the files manually

**Pull request closed without merging**
